name: CI
on:
  push: {}
jobs:
  check_rotating_lights:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Report uses of rotating light
    - run: git grep -n $'\xf0\x9f\x9a\xa8' | sed -E 's/^([^:]+):([^:]+):\s*/::error file=\1,line=\2::/'
    # Fail build if rotating light is used
    - run: "! git grep -q $'\xf0\x9f\x9a\xa8'"
